const en = {
    username: 'Username',
    email: 'Email',
    password: 'Password',
    repeatpassword: 'Repeat Password',
    register: 'Register',
    passwordsMatchError: 'Passwords do not match.',
    login: 'Login',
    forgotpassword: 'I Forgot my Password',
    emailVerification: 'Email Verification',
    emailVerificationMessage: 'Please verify your email in order to login.',
    passwordReset: 'Password Reset',
    passwordResetMessage: 'Please check your email in order to reset your password.',
    warning: 'Warning!',
    themeMessage: 'In order to change theme, the app must be restarted. Press OK to Restart.',
    home: 'Home',
    deletePost: 'Delete Post',
    areYouSure: 'Are you sure?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    ok: 'OK',
    deletedPostAlready: 'This Post has been deleted already.',
    postDeleted: 'Post Deleted!',
    postDeletedMessage: 'Your Post has been deleted successfully!',
    like: 'Like',
    comment: 'Comment',
    commentsTitle: 'Comments',
    addPostTitle: 'Add a Post',
    addPost: `What's on your mind?`,
    post: 'Post',
    postPublishedTitle: 'Post Published!',
    postPublishedMessage: 'Your Post has been published successfully!',
    takePhoto: 'Take Photo',
    choosePhoto: 'Choose Photo',
    message: 'Message',
    messages: 'Messages',
    profileTitle: 'Profile',
    editProfileTitle: 'Edit Profile',
    edit: 'Edit',
    logout: 'Logout',
    posts: 'Posts',
    followButtonText: 'Follow',
    followingButtonText: 'Following',
    followers: 'Followers',
    following: 'Following',
    aboutmeDefault: 'Go to the Edit Profile Page to change this text :)',
    changeUsername: 'Change Username',
    changeEmail: 'Change Email',
    changePasswordCurrent: 'Current Password (Needed to change Email/Password)',
    changePasswordNew: 'New Password',
    changeAboutme: 'About me',
    update: 'Update',
    error: 'Error!',
    permissionsErrorStorage: 'Please give storage permissions to the application.',
    permissionsErrorCamera: 'Please give camera permissions to the application.',
    errorPostEmpty: 'You need to either have Text or an Image in your post.',
    accountChanged: 'Account Changed',
    accountChangedError: 'Account Changed (ERROR!)',
    emailAndPasswordChanged: 'Both your Email and Password were changed. Please verify your new Email and re-login using your new Email and Password into the app.',
    emailChanged: 'Your Email was changed. Please verify your new Email and re-login using your new Email into the app.',
    emailChangedPasswordError: 'Your Email was changed. But there was an error changing your Password. Please verify your new Email and re-login into the app. ERROR: ',
    passwordChanged: 'Your Password was changed. Please re-login into the app using your new Password.',
    passwordChangedEmailError: 'Your Password was changed. But there was an error changing your Email. Please re-login into the app using your new Password. ERROR: ',
    emailAndPasswordError: 'There was an error changing both your Email and Password.',
    emailError: 'EMAIL ERROR: ',
    passwordError: ' PASSWORD ERROR: ',
    usernameError: 'Username cannot be empty.',
    profileUpdated: 'Profile Updated!',
    profileUpdatedMessage: 'Your Profile was updated successfully!'
}

const pt = {
    username: 'Nome de utilizador',
    email: 'Email',
    password: 'Palavra-Passe',
    repeatpassword: 'Repetir Palavra-Passe',
    register: 'Registrar',
    passwordsMatchError: 'As Palavras-Passe não coincidem.',
    usernameErrorAlreadyExists: 'O Nome de Utilizador já existe.',
    login: 'Entrar',
    forgotpassword: 'Esqueci-me da Palavra-Passe',
    emailVerification: 'Verificação de Email',
    emailVerificationMessage: 'Por favor verifica o teu email para entrar na Aplicação.',
    passwordReset: 'Reposição de Palavra-Passe',
    passwordResetMessage: 'Por favor verifica o teu email para repor a tua Palavra-Passe.',
    warning: 'Aviso!',
    themeMessage: 'Para mudar de tema, a aplicação terá de reiniciar. Clique em OK para reiniciar.',
    home: 'Página Inicial',
    deletePost: 'Eliminar Post',
    areYouSure: 'Tens a certeza?',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    ok: 'OK',
    deletedPostAlready: 'Este Post já foi eliminado.',
    postDeleted: 'Post Eliminado!',
    postDeletedMessage: 'O teu Post foi eliminado com sucesso!',
    like: 'Gostar',
    comment: 'Comentar',
    commentsTitle: 'Comentários',
    addPostTitle: 'Adicionar Publicação',
    addPost: 'O que é que está na tua mente?',
    post: 'Publicar',
    postPublishedTitle: 'Post publicado!',
    postPublishedMessage: 'O seu Post foi publicada com sucesso!',
    takePhoto: 'Tirar Foto',
    choosePhoto: 'Escolher Foto',
    message: 'Mensagem',
    messages: 'Mensagens',
    profileTitle: 'Perfil',
    editProfileTitle: 'Editar Perfil',
    edit: 'Editar',
    logout: 'Sair',
    posts: 'Publicações',
    followButtonText: 'Seguir',
    followingButtonText: 'A Seguir',
    followers: 'Seguidores',
    following: 'A Seguir',
    aboutmeDefault: 'Edita o teu Perfil para alterares este texto :)',
    changeUsername: 'Mudar Nome de Utilizador',
    changeEmail: 'Mudar Email',
    changePasswordCurrent: 'Palavra-Passe Atual (Necessário para alterar Email/Palavra-Passe)',
    changePasswordNew: 'Palavra-Passe Nova',
    changeAboutme: 'Sobre mim',
    update: 'Atualizar',
    error: 'Erro!',
    permissionsErrorStorage: 'Por favor dá permissões de armazenamento à aplicação.',
    permissionsErrorCamera: 'Por favor dá permissões de acesso à câmera.',
    errorPostEmpty: 'Precisas de ter texto ou uma imagem no teu post.',
    accountChanged: 'Conta Alterada',
    accountChangedError: 'Conta Alterada (ERRO!)',
    emailAndPasswordChanged: 'O teu Email e a tua Palavra-Passe foram ambos alterados. Por favor verifica o teu novo email e entra novamente na aplicação com a nova Palavra-Passe.',
    emailChanged: 'O teu Email foi alterado. Por favor verifica o teu novo email e entra novamente na aplicação.',
    emailChangedPasswordError: 'O teu Email foi alterado, mas houve um erro ao tentar alterar a tua Palavra-Passe. Por favor verifica o teu novo email e entra novamente na aplicação. ERRO: ',
    passwordChanged: 'A tua Palavra-Passe foi alterada. Por favor entra novamente na aplicação com a nova Palavra-Passe.',
    passwordChangedEmailError: 'A tua Palavra-Passe foi alterada, mas houve um erro ao tentar alterar o teu Email. Por favor entra novamente na aplicação com a nova Palavra-Passe. ERRO: ',
    emailAndPasswordError: 'Houve um erro ao tentar alterar a tua Palavra-Passe e o teu Email.',
    emailError: 'ERRO DO EMAIL: ',
    passwordError: ' ERRO DA PALAVRA-PASSE: ',
    usernameError: 'O Nome de Utilizador não pode estar vazio.',
    profileUpdated: 'Perfil Atualizado!',
    profileUpdatedMessage: 'O teu Perfil foi atualizado com sucesso!'
}

export { en, pt }