const en = {
    username: 'Username',
    email: 'Email',
    password: 'Password',
    repeatpassword: 'Repeat Password',
    register: 'Register',
    login: 'Login',
    forgotpassword: 'I Forgot my Password',
    home: 'Home',
    like: 'Like',
    comment: 'Comment',
    commentsTitle: 'Comentários',
    addPostTitle: 'Add a Post',
    addPost: `What's on your mind?`,
    post: 'Post',
    takePhoto: 'Take Photo',
    choosePhoto: 'Choose Photo',
    message: 'Message',
    messages: 'Messages',
    profileTitle: 'Profile',
    editProfileTitle: 'Edit Profile',
    edit: 'Edit',
    logout: 'Logout',
    posts: 'Posts',
    followButtonText: 'Follow',
    followingButtonText: 'Following',
    followers: 'Followers',
    following: 'Following',
    aboutmeDefault: 'Go to the Edit Profile Page to change this text :)',
    changeUsername: 'Change Username',
    changeEmail: 'Change Email',
    changePasswordCurrent: 'Current Password (Needed to change Email/Password)',
    changePasswordNew: 'New Password',
    changeAboutme: 'About me',
    update: 'Update'
}

const pt = {
    username: 'Nome de utilizador',
    email: 'Email',
    password: 'Palavra-Passe',
    repeatpassword: 'Repetir Palavra-Passe',
    register: 'Registrar',
    login: 'Entrar',
    forgotpassword: 'Esqueci-me da Palavra-Passe',
    home: 'Página Inicial',
    like: 'Gostar',
    comment: 'Comentar',
    commentsTitle: 'Comentários',
    addPostTitle: 'Adicionar Publicação',
    addPost: 'O que é que está na tua mente?',
    post: 'Publicar',
    takePhoto: 'Tirar Foto',
    choosePhoto: 'Escolher Foto',
    message: 'Mensagem',
    messages: 'Mensagens',
    profileTitle: 'Perfil',
    editProfileTitle: 'Editar Perfil',
    edit: 'Editar',
    logout: 'Sair',
    posts: 'Publicações',
    followButtonText: 'Seguir',
    followingButtonText: 'A Seguir',
    followers: 'Seguidores',
    following: 'A Seguir',
    aboutmeDefault: 'Edita o teu Perfil para alterares este texto :)',
    changeUsername: 'Mudar Nome de Utilizador',
    changeEmail: 'Mudar Email',
    changePasswordCurrent: 'Palavra-Passe Atual (Necessário para alterar Email/Palavra-Passe)',
    changePasswordNew: 'Palavra-Passe Nova',
    changeAboutme: 'Sobre mim',
    update: 'Atualizar'
}

export { en, pt }